### ISSUE TITLE
Add deadline shift setting for agent in edo

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1367]

**Comment by sergeyf-QA** [comment]
**Summary:**
- deadline shift for an agent may be added using PUT 
/{culture}/api/{v}/admin/agencies/{agencyId}/agents/{agentId}/system-settings/availability-search putting "customDeadlineShift" parameter in request JSON
- GET /{culture}/api/{v}/admin/agencies/{agencyId}/agents/{agentId}/system-settings/availability-search shows "customDeadlineShift" parameter in response
- "customDeadlineShift" may be positive and negative
- "customDeadlineShift" and agency deadline shift sum with each other 
- in case the sum of "customDeadlineShift" and agency deadline shift >0 then the sum result is changed to 0, e.g. 

If the root agency has an offset of -3 and the agent has an offset of 100, then the result will be (-3 + 100) = 97
But since it's greater than 0, then sum deadline shift will change to 0

**OK on DEV.**
