### ISSUE TITLE
Have to allow to see a 3d search step for ReadOnly Agencies

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1518]
A ReadOnly Agency can see a 3d search step in an Agentt App.
They can check an availability and an UI options but can't book.

A read only agency will see a notification: ''If you want to book this accommodation contract please contact with your Happy Travel manager'' instead of a booking button

A notification text can be discussed

**Comment by DaniyarAskarov** [comment]
https://github.com/happy-travel/edo/issues/1886
Solution, but need to think about notification in front-end

**Comment by alexander-plekhanov** [comment]
Impossible to fix, no data from API (code 400)

**Comment by alexander-plekhanov** [comment]
Fixed after API fix.

**Comment by DenisVelinen** [comment]
On dev. environment. If an agency has a Read Only status his agents will see the message "Please contact your Happy Travel manager if you want to book this accommodation" instead of pay button and won't see the fields of guest details.
<img width="946" alt="Снимок экрана 2022-06-21 в 21 44 18" src="https://user-images.githubusercontent.com/17127277/174874984-7096d3e2-d938-4a90-b422-1c9afcbbaedc.png">
