### ISSUE TITLE
An administrator with the Accommodation duplicates corrector role doesn’t have access to the /rating-types /deactivation-reason-types methods

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#1565]
**How to reproduce:**
1. Log in admin who has "Accommodation duplicates corrector" role (or change the roles with your admin);
2. Open browser’s dev. tools panel;
3. Go to Mapper tab.

**Expected result:**
An administrator with "Accommodation duplicates corrector" role should have access to all the methods which need to work with the mapper in the admin app.

**Actual result:**
An administrator with the Accommodation duplicates corrector role doesn’t have access to the /rating-types /deactivation-reason-types methods
These methods are needed to use the RATING and DEACTIVATION REASONS fields

![Image](https://user-images.githubusercontent.com/17127277/175519652-7868718c-4ae0-406f-8733-abc86974875c.png)

**Comment by DaniyarAskarov** [comment]
I added to "Accommodation duplicates corrector" role AccommodationsManagement permission. Because that permission check in this endpoints. Now it should works. 
By the way what is the difference btw "Accommodation duplicates corrector" and "Accommodation Mapping Manager" roles. By now they difference just in one permission "Locations Management"?

**Comment by ViTsvetkova** [comment]
minor
