### ISSUE TITLE
Check the PROD

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1648]
QA must check and analyze the PROD by this task
https://github.com/happy-travel/agent-app-project/issues/1542

**Comment by DenisVelinen** [comment]
"Oops! Something went wrong!" is still happening after 30 minutes when you want to view offers from a hotel that has not been visited before, whose offers have not been saved in the cache. However, if someone has previously viewed offers from that hotel, the data comes from the cache. 

For example, previously viewed offers of Movenpick Hotel Jumeirah Beach
https://edo.happytravel.com/en/api/1.0/accommodations/availabilities/searches/2fdb9aa4-c896-4523-88dc-4dc7406b2612/results/Accommodation_3142081 respectively after 30 minutes you can see them as well. But going to the offers of Nassima Towers Hotel Apartments https://edo.happytravel.com/en/api/1.0/accommodations/availabilities/searches/2fdb9aa4-c896-4523-88dc-4dc7406b2612/results/Accommodation_3141989 returns an empty array of offers and the interface shows Oops! Something went wrong! No accommodations available.
<img width="1172" alt="Снимок экрана 2022-08-02 в 11 31 47" src="https://user-images.githubusercontent.com/17127277/182336242-24dfc8cb-dbd8-4118-802b-5e1467de3785.png">

**Comment by DenisVelinen** [comment]
How to.

On https://happytravel.com/
1. Do a search with any popular parameters. For example, Dubai, The United Arab Emirates, Oct 15 – Oct 16, 2 adults, any nationality and residency
2. Go to any hotel to view its offers (second search step)
3. Go back to view all search results (first search step)
4. Wait more than 30 minutes
5. Navigate to the same hotel as you viewed the results in step two. Go to any hotel to see all the offers in it

**Comment by DaniyarAskarov** [comment]
During deal with this issue I found a few problems:

1) The second search step restarts search for certain accommodation but clear cache in mongo for whole list of hotels by this supplier.
2) Solving first problem uncovered next problem: Each restarting search for certain accommodation saves cache in connectrors only for this specific hotel.  When next hotel would be tried to get from connector it procceeded an Error (Status = "Unknown"). Because AvailabilityRequest would be found but RoomContractSets for this specific AccommodationId wouldn't be found.
3) The third problem comes from second, we need to store results in cache by composite key ("AvailabilityId" and "AccommodationId")

**Comment by DenisVelinen** [comment]
Correcting the problems will be done in other tasks, as the solution requires many changes.
