### ISSUE TITLE
In AccountBalanceAuditLogs, add a record of agency transfers funds to sub-agencies

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#1793]
If an agency transfers funds from its balance to a sub-agency balance, this transaction is not recorded in the "AccountBalanceAuditLogs" table, so it is not shown in the "Account History" tab on the agency page in UI. This confuses the numbers of the history of balance (see pic.):

![Image](https://user-images.githubusercontent.com/17127277/189322907-3010fdb8-a0ce-4521-adb8-d5ef5077b4d6.png)

**Comment by DenisVelinen** [comment]
**How to do.**

On https://dev.happytravel.com/
1. Log in an agent whose agency has a subagency;
2. Go to agency settings and to the "Subagencies" tab;
3. Remember agency's balance;
4. Transfer funds to any subagency.

On https://manage-dev.happytravel.com/

5. Log in to admin app;
6. Find the agency where the transfer of funds was made;
7. Go to the "Account History" tab and find the record of the transfer made (the list is sorted from the earliest to the newest).

**Expectations:**
- the agency's balance should be reduced by the amount of the transfer;
- in "Account History" tab there should be a record of the transfer to the subagency.

**Comment by ViTsvetkova** [comment]
https://happytravel.freshdesk.com/a/tickets/663

**Comment by sergeyf-QA** [comment]
@DFSko 
when I try to transfer money to a subagency then 
POST https://edo-dev.happytravel.com/en/api/1.0/agency-accounts/148/transfer/400 returns
{"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"Internal Server Error","status":500,"detail":"A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.","instance":"/en/api/1.0/agency-accounts/148/transfer/400","spanId":"a6dc70d99971efee","traceId":"c02493d3048baa3e3b330d0f5f88d175","requestId":"0HMKIVBBMLIDC:00000013","x-request-id":[],"StackTrace":"   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList\u00601 entriesToSave, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func\u00604 operation, Func\u00604 verifySucceeded, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at HappyTravel.Edo.Api.Services.Payments.Accounts.AccountBalanceAuditService.Write[TEventData](AccountEventType eventType, Int32 accountId, Decimal amount, ApiCaller apiCaller, TEventData eventData, String referenceCode) in /src/Api/Services/Payments/Accounts/AccountBalanceAuditService.cs:line 36\n   at HappyTravel.Edo.Api.Services.Payments.Accounts.AccountPaymentProcessingService.\u003C\u003Ec__DisplayClass3_0.\u003C\u003CTransferToChildAgency\u003Eg__WriteAuditLog|9\u003Ed.MoveNext() in /src/Api/Services/Payments/Accounts/AccountPaymentProcessingService.cs:line 187\n--- End of stack trace from previous location ---\n   at CSharpFunctionalExtensions.AsyncResultExtensionsBothOperands.Tap[T](Task\u00601 resultTask, Func\u00602 func)\n   at HappyTravel.Edo.Api.Infrastructure.FunctionalExtensions.ResultTransactionExtensions.\u003C\u003Ec__DisplayClass10_0\u00601.\u003C\u003CWithTransactionScope\u003Eb__0\u003Ed.MoveNext() in /src/Api/Infrastructure/FunctionalExtensions/ResultTransactionExtensions.cs:line 153\n--- End of stack trace from previous location ---\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.\u003C\u003Ec__DisplayClass33_0\u00602.\u003C\u003CExecuteAsync\u003Eb__0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func\u00604 operation, Func\u00604 verifySucceeded, TState state, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func\u00604 operation, Func\u00604 verifySucceeded, TState state, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func\u00604 operation, Func\u00604 verifySucceeded, CancellationToken cancellationToken)\n   at HappyTravel.Edo.Api.Infrastructure.FunctionalExtensions.ResultTransactionExtensions.BindWithTransaction[T,TK](Result\u00601 target, DbContext context, Func\u00602 f) in /src/Api/Infrastructure/FunctionalExtensions/ResultTransactionExtensions.cs:line 97\n   at HappyTravel.Edo.Api.Infrastructure.FunctionalExtensions.ResultLockExtensions.WithLock[TResult](IEntityLocker locker, String lockerName, Func\u00601 operation, ValueTuple\u00602[] locks)\n   at HappyTravel.Edo.Api.Infrastructure.FunctionalExtensions.ResultLockExtensions.WithLock[TResult](IEntityLocker locker, String lockerName, Func\u00601 operation, ValueTuple\u00602[] locks) in /src/Api/Infrastructure/FunctionalExtensions/ResultLockExtensions.cs:line 82\n   at HappyTravel.Edo.Api.Infrastructure.FunctionalExtensions.ResultLockExtensions.BindWithLock[TInput1,TInput2,TOutput](Task\u00601 target, IEntityLocker locker, Func\u00602 func)\n   at HappyTravel.Edo.Api.Services.Payments.Accounts.AccountPaymentProcessingService.TransferToChildAgency(Int32 payerAccountId, Int32 recipientAccountId, MoneyAmount amount, AgentContext agent) in /src/Api/Services/Payments/Accounts/AccountPaymentProcessingService.cs:line 106\n   at HappyTravel.Edo.Api.Services.Payments.Accounts.AccountPaymentService.TransferToChildAgency(Int32 payerAccountId, Int32 recipientAccountId, MoneyAmount amount, AgentContext agent) in /src/Api/Services/Payments/Accounts/AccountPaymentService.cs:line 257\n   at HappyTravel.Edo.Api.Controllers.AgentControllers.AgencyAccountsController.TransferToChildAgency(Int32 payerAccountId, Int32 recipientAccountId, MoneyAmount amount) in /src/Api/Controllers/AgentControllers/AgencyAccountsController.cs:line 45\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeActionMethodAsync\u003Eg__Logged|12_1(ControllerActionInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeNextActionFilterAsync\u003Eg__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeInnerFilterAsync\u003Eg__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeNextResourceFilter\u003Eg__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilder.\u003C\u003Ec.\u003C\u003CBuildPipeline\u003Eb__8_0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at HappyTravel.Edo.Api.Infrastructure.Middlewares.AgentRequestLoggingMiddleware.InvokeAsync(HttpContext context, IAgentContextInternal agentContextService) in /src/Api/Infrastructure/Middlewares/AgentRequestLoggingMiddleware.cs:line 39\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"}

**Comment by sergeyf-QA** [comment]
**Summary:**
- now when money are transferred to a subagency an event records to the "AccountBalanceAuditLogs" table
-  in the "Account History" tab on the agency page in admin panel is record about transfer

**OK on DEV.**
