### ISSUE TITLE
Fix 403 for Additional Markup Manager for some endpoints

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1903]
**How to reproduce:**
- go to https://manage-dev.happytravel.com/markups/agent-markups/create as an admin with **Additional Markup Manager** role
- try to fill fields there

**Expected result:**
- 200 OK for these endpoints for **Additional Markup Manager** role because in other case it is impossible to create agent markup

**Actual result:**
GET https://edo-dev.happytravel.com/en/api/1.0/admin/agencies/801/agents
GET https://edo-dev.happytravel.com/en/api/1.0/admin/locations/countries
GET https://edo-dev.happytravel.com/en/api/1.0/admin/locations/markets
return 403

**Comment by AlexeyShok** [comment]
Added ViewAgents permission to role Additional Markup Manager for fix GET https://edo-dev.happytravel.com/en/api/1.0/admin/agencies/801/agents. Removed MarkupManagement permission from endpoint GET https://edo-dev.happytravel.com/en/api/1.0/admin/locations/countries. The endpoint GET https://edo-dev.happytravel.com/en/api/1.0/admin/locations/markets will return a 403 error because it was decided not to be used. It is necessary to remove his call on the front if the admin does not have the MarkupMamagement permission.

**Comment by sergeyf-QA** [comment]
**Summary:**
- now an admin with **Additional Markup Manager** role does not see 403 errors on https://manage-dev.happytravel.com/markups/agent-markups/create during creation agent markup

**OK on DEV.**
