### ISSUE TITLE
Add notifications via NotificationCenter for Administrator

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#220]
We need add SignalR administrator notifications and add/transfer sending email via NotificationCenter for next events:

EDO: Administrator invitation;
EDO: Master agent successful registration;
EDO: Bookings Administrator Summary Notification;
EDO: BookingAdministratorPaymentsSummary;
EDO: Booking Cancelled (to Reservations);
EDO: Booking Finalized (to Reservations);
EDO: Credit card payment received (Administrator).
EDO: BookingManualCorrectionNeeded.

And for agents:
EDO:Booking summary report for agent.

A more detailed description can be found here:
happy-travel/edo#472

**Comment by sergeyf-QA** [comment]
**Summary:**
these notifications are for:
EDO: Administrator invitation=16 - OK
EDO: Master agent successful registration=17 - OK
EDO: Bookings Administrator Summary Notification=18 - OK
EDO: BookingAdministratorPaymentsSummary=19 - can not check because the report is sending only 1st day of every month - will fix it in another ticket in future
EDO: Booking Cancelled (to Reservations)=20 - can not check because supplier must cancel a booking on his side
EDO: Booking Finalized (to Reservations)=21 - can not check because supplier must finalize a booking on his side
EDO: Credit card payment received (Administrator)=22- OK
EDO: BookingManualCorrectionNeeded=23 - OK

And for agents:
EDO:Booking summary report for agent=24 - OK

**OK on DEV.**
