### ISSUE TITLE
Change Invoice and Voucher Layouts

### ISSUE THREAD

**Issue by kirillta** [happy-travel/agent-app-project#231]
Amend invoice and voucher email templates with the following changes:

#### Invoice

1. Hide an empty _email_ or _address_ field in the _Bill to_ section
2.  Leave only a contract description in the _Room_ cell of the table and a meal plan if any (nothing like `Not specified` must left)

#### Voucher

1. Replace the _Deadline Date_ cell with a supplier confirmation number (or our if the supplier one is empty)
2. Add `Room type:` words to the contract description right below the table.
3. Move `Meal Plan` description one line after the _room type_ field.
4. Hide the _Board basis_ field, if meal plan is at place.
5. Board basis values are not deserialized to string properly (for instance `HalfBoard` instead of `Half Board`).
6. Remove the duplicated _Room type_ field from below the passenger section.

Also, I would like to see the unified date format in both template: dd-month-yyyy like 10 January 2021

**Comment by DenisSychev** [comment]
It was decided not to add Room type to the table, not to move the Meal Plan under the table because the look needs to be redone to account for multiple rooms.
Other changes have been made and are available on the website.
<img width="446" alt="Снимок экрана 2021-05-26 в 11 54 28" src="https://user-images.githubusercontent.com/17127277/119632865-df046880-be19-11eb-9d28-97a27f469de8.png">
<img width="334" alt="Снимок экрана 2021-05-26 в 11 58 25" src="https://user-images.githubusercontent.com/17127277/119632876-e0ce2c00-be19-11eb-99f1-14fcb8f5d18c.png">

**Comment by DenisSychev** [comment]
New versions of the Voucher and Invoice emails are available and working on the https://dev.happytravel.com and https://happytravel.com
