### ISSUE TITLE
Create a structured draft API docs 

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#370]
Need to create a structure with partial fullfillment about our availability search flow.
It should contain the main concepts, steps description, without explaining used models.
Later we'll fill it with the valid explanation.
For best API docs examples see docs for ETG, Rakuten in #resources channel

**Comment by Raibo** [comment]
### Searching.
This process provides means to find suitable accommodation and room, see details and price for booking.

At first, id of an accommodation or location must be retrieved.
This can be done via static data service or predictions service.

Search takes place in 3 steps:
1. **Wide availability search**.
This step initiates the search process and finds all accommodations that fit the search criteria and shows accommodation details and room contracts, so that an accommodation can be picked.
2. **Room selection**.
Once an accommodation is picked, this step provides with more accurate details about the accommodation and it's room contracts, so that a room or rooms can be picked.
3. **Booking evaluation**.
Once a room is picked, this step evaluates the room contract and provides final price details about the room contract. The room or rooms can now be booked.

### Wide availability search.

**Start search**.
This step initiates search, which requires following criteria:
1. Id of either location or accommodation.
2. Nationality.
3. Residency.
4. Dates of check in and check out.
5. Information about rooms: adults and children count for each of them.

If location id was provided, then search occurs across different accommodations within given location.
If accommodation id was provided, then search occurs within this accommodation only.

In response to initial search request, search id is returned.
This id identifies the initiated search with given criteria and is used for later search status or results retrieval.

**Check search status**.
Search may take some time. Search id can be used to request search status and quantity of already found results.
At this step, the data is cached, so latest changes may not be reflected in it.

**Retrieve search results**.
If the search process is completed or partially completed, results, which are present at the moment, can be retrieved using the search id.
These results contain information about found accommodations and their corresponding room contracts.

### Room selection.
This step searches the exact accommodation to retrieve more details about the accommodation and it's room contracts, which are also more accurate.
The data is retrieved with a single request, using search id and accommodation id.

### Booking evaluation.
This step evaluates and show most accurate price and details for an exact room contract. This concludes the search process.
The data is retrieved with a single request, using search id, accommodation id and room contract id.

**Comment by Raibo** [comment]
### Booking.
This takes place after the search process is finished. The data retrieved via search is used to book.

The booking can be made in 3 different ways, depending on payment option.

### Booking using credit card.
Takes place in 3 steps:
1. Booking registration.
The booking is registered, but not yet confirmed. Reference code is returned, which identifies the newly registered booking.
2. Payment.
The payment is made for the booking, using the reference code.
3. Finalization.
If the payment was successful, the booking is confirmed, which concludes the booking process.


### Booking using Happy Travel account.
The booking is confirmed in one step, reference code is returned.

- Happy Travel account is required for this option.
- If the deadline of a room contract has already passed, then the account balance must be sufficient for the booking.
- If the deadline of a room contract has not yet passed, then the account balance must be positive at the moment of booking, but not necessarily sufficient. However, the account balance must be sufficient for the booking at the deadline moment, otherwise the booking is cancelled.


### Booking using offline payment.
The booking is confirmed in one step, reference code is returned.

- Can not be used to book room contracts with already passed deadline.
- Can be payed with credit, instead of offline payment.
- The booking must be either payed with credit card, or an administrator must confirm the offline payment before the moment of deadline, otherwise the booking is cancelled.

**Comment by mingazhev** [comment]
@oleg1std @hasmikharutyunyan @kirillta @AlexeyShok could you have a look please?
Is this draft ok for the start and contains useful and clear information for our potential API client?

**Comment by kirillta** [comment]
I expect the following changes:
1. More explicit mention of caching and its timeouts due the search stage
2. Only account bookings correspond API queries
3. No cancellations and status change handlers so far

**Comment by Raibo** [comment]
All fixed, except for status changes descriptions, but we'll just add the diagram there, no need to bring it here in the comments.

**Comment by mingazhev** [comment]
Ok as a draft
