### ISSUE TITLE
Reference open telemetry and open tracing metapackage in all services

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#382]
+ check jaeger agent is configured.
List all the services checked in the comments of the tasks for @evm-andrey to check that agent is configured and configure if needed

**Comment by DFSko** [comment]
Added https://github.com/happy-travel/telemetry package to repositories:

https://github.com/happy-travel/edo
https://github.com/happy-travel/travelgatex-channel
https://github.com/happy-travel/travelgatex-connector
https://github.com/happy-travel/iwtx-connector
https://github.com/happy-travel/nakijin
https://github.com/happy-travel/columbus-connector
https://github.com/happy-travel/odawara
https://github.com/happy-travel/tsutsujigasaki
https://github.com/happy-travel/uwajima
https://github.com/happy-travel/gifu
https://github.com/happy-travel/rakuten-connector
https://github.com/happy-travel/netstorming-connector
https://github.com/happy-travel/etg-connector
https://github.com/happy-travel/jumeirah-connector

**Comment by sergeyf-QA** [comment]
**Summary:**
telemetry changes were added to

https://github.com/happy-travel/edo
https://github.com/happy-travel/travelgatex-channel
https://github.com/happy-travel/travelgatex-connector
https://github.com/happy-travel/iwtx-connector
https://github.com/happy-travel/nakijin
https://github.com/happy-travel/columbus-connector
https://github.com/happy-travel/odawara
https://github.com/happy-travel/tsutsujigasaki
https://github.com/happy-travel/uwajima
https://github.com/happy-travel/gifu
https://github.com/happy-travel/rakuten-connector
https://github.com/happy-travel/netstorming-connector
https://github.com/happy-travel/etg-connector
https://github.com/happy-travel/jumeirah-connector
https://github.com/happy-travel/fukuoka

in https://github.com/happy-travel/osaka no telemetry because there is no redis

**OK on DEV.**
