### ISSUE TITLE
Error while getting deadline [illusions]

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#408]
1. Get accommodation with search data:
`Graph Hotel Bangkok, Bangkok, Thailand - 08.07 - 10.07 - Supplier: Illusions - 2 guests `
2. Push button 'Cancellation Deadline'

**AR**: Get error - https://sentry.happytravel.com/organizations/happytravel/issues/1713/events/e8290d1639e243d5b3fe219ea45dc500/?project=4 
<img width="1440" alt="Screenshot 2021-07-06 at 16 43 43" src="https://user-images.githubusercontent.com/38030865/124610785-76c58f80-de79-11eb-8235-09d0c865ac8d.png">

3. Push button 'Cancellation Deadline' on second step 
**AR**: Get error - https://sentry.happytravel.com/organizations/happytravel/issues/2585/events/d15aaa6bbd2a43f6b7432cf5c1dca0d8/?project=4

<img width="1427" alt="Screenshot 2021-07-06 at 16 43 12" src="https://user-images.githubusercontent.com/38030865/124610679-63b2bf80-de79-11eb-911c-f406724d4772.png">

**Comment by Raibo** [comment]
Both cases fails because Illusions respond with "Records Not Found" when requesting deadline info.

Here is why error messages are different.
When request fails during 2nd step, the original error message ("Records Not Found") is returned.
When request fails during 1st step, attempt to find data for 2nd step is executed, but no data for 2nd step exists yet, so it fails to find room contract set and returns this error message instead
