### ISSUE TITLE
Cleanup sentry errors - remove not critical

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#424]
Sentry is overloaded with thousands of errors that are not critical and has nothing to with - like Illusions errors and etc.
Need to check all the errors by last 2 weeks and create a list of errors not to send to sentry.
Approve this list with backend team and change log level for such errors to write them only to the Elastic kibana.

**Comment by Raibo** [comment]
In Edo:
- Remove everything that is caused by an another service, e.g. "Could not evaluate booking, error on connector". Because we'll get this error on that connector and better deal with it there.  
- Remove everything that puts a booking in error state, because this will be supervised by somebody anyway, no need to see this in sentry.

**Comment by Raibo** [comment]
The majority of mess in sentry are exceptions, which are currently not grouped or organized.
My suggestion is to get the deepest service from the stack of an exception and let Sentry to group issues by that.
If no service was found, then group as not-in-service.
