### ISSUE TITLE
"You cant login this panel with Agents account" message appears when you login panel for first time

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#468]
**How to reproduce:**
- login as admin and invite a new one
- proceed admin registration

**Actual result:**
- when invited admin completed registration then "You cant login this panel with Agents account" message appears together with 403 errors for several endpoints

**Expected result:**
- no 403 errors
- no "You cant login this panel with Agents account" message because this is an invited administrator, not an agent

**Comment by mingazhev** [comment]
@cyberkarma could you have a look?
The problem is that `check for adminness` is executed even when the admin tries to register by invitation.
In this case new invited administrator should be able to proceed accepting invitation without any errors and additional checks.

And the message should be rethinked, I suppose, to something like `You are not registered in the admin panel` or something similar

**Comment by mingazhev** [comment]
@sergeyf-QA could you check if still actual?

**Comment by sergeyf-QA** [comment]
@mingazhev 
the issue is not actual now
