### ISSUE TITLE
Add a documentation for existing cron-based services for EDO

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#800]
We have different cron-based services that use EDO endpoints to work.
Some start once a day, some start every minute.

Need to write separately
1.  about booking status refreshing service (how works, for which reason is used)
2. About paying methods from kanazawa - when we capture money for each booking, when try to cancel if balance is insufficient. When we cancel offline bookings
3. About notifications we send every day

**Comment by Raibo** [comment]
# Booking status automatic refresh.
Is supported by Uwajima service.
The service is launched once every minute. (This does not mean that a booking is refreshed every minute though)

## Why we need it?
We need to constantly refresh information about bookings statuses because certain booking statuses are changed by the supplier.
Constant status refreshing is the way to stay in sync.

## Which bookings are refreshed?
Criteria for bookings to be automatically refreshed:
1. Was not refreshed recently
2. Check in date is in the future
3. Current status is one of the following: Pending, PendingCancellation, WaitingForResponse, Confirmed
4. Supplier of the booking is not turned off for automatic status updates. (Currently no such suppliers on dev)

## How the refreshing is made?
A booking status request is sent to the supplier.
The response is then processed.
Booking status is updated according to status in the response.

**Comment by Raibo** [comment]
# Capturing, charging and cancelling bookings automatically.
Is supported by **Kanazawa** service.
The service is launched **once every day**.

## Why do we need it?
When the deadline comes for a booking, the booking can no longer be cancelled free of charge.
Therefore the payment must be secured at this point for HappyTravel to avoid financial risks. Otherwise, the booking must be cancelled.

## Different payment methods
Securing the payment happens differently for different payment options, or payment methods.

There are three payment options for bookings: credit card, virtual account and offline.
- Credit card speaks for itself.
- Virtual account means the money is charged from the account, which is replenished in advance by a bank transfer or other means.
- Offline means that after a booking was created, it must be payed with a bank transfer, or other means, specifically intended for this booking. The HappyTravel office has to approve that the payment was indeed made for the booking.

## Chanrging and cancellation explanation
Generally, at the point of booking deadline, the payment is either secured, or the booking is cancelled.

For credit card bookings, the money is authorized right after the booking is created.
When the deadline date comes, the already authorized money is just captured.
This is a reliable scheme, so there is no need to cancel credit card bookings automatically due to payment issues.
The money is not captured right after because it introduces costs for refund operation and therefore better be done later.

For offline and virtual account payed bookings, however, it is possible that the payment is not possible when the deadline date comes.
Therefore there is automatic cancellation procedure for bookings with such payment methods.
For virtual account bookings this happens when the balance is insufficient.
For offline bookings this happens when the HappyTravel office did not approve that the booking was payed.

## Chanrging and capturing criteria
Criteria for a credit card booking to be captured:
1. Status is one of the following: Pending, Confirmed, WaitingForResponse
2. Payment status is Authorized
3. Either check in or deadline date has come

Criteria for a virtual account booking to be charged:
1. Status is one of the following: Pending, Confirmed, WaitingForResponse
2. Payment status is NotPaid
3. Deadline date has come

## Cancellation criteria
Criteria for a booking to be cancelled due to payment issues:
1. Status is Confirmed
2. Payment status is one of the following: NotPaid, Refunded, Voided
3. Payment method is one of the following: CreditCard, Offline
4. Deadline date has come

**Comment by Raibo** [comment]
# Daily reports.
Is supported by **Kanazawa** service.
These reports are sent once every day.

## Agent summary
For agents with a role that allows receiving booking summary.
An agent receives summary for their agency's bookings.

Includes every booking passing the following criteria:
1. Payment type is VirtualAccount.
2. Payment status is **not** Captured.
3. Status is one of the following: WaitingForResponse, Pending, Confirmed, ManualCorrectionNeeded, PendingCancellation
4. Deadline date (or check in date if no deadline date available) is within 24 hours from current time.

Report also includes current virtual account balance and future expected balance after all bookings are paid.
If the expected balance is negative, an additional warning is included.

## Administrator summary
Includes every booking passing the following criteria:
1. Deadline date (or check in date if no deadline date available) is within 5 days from current time.
2. Status is one of the following: WaitingForResponse, Pending, Confirmed, ManualCorrectionNeeded, PendingCancellation

Includes information about booking itself, agent and agency, which a booking belongs to.

The summary is sent to specifically configured email addresses. (CcNotificationAddresses)

## Administrator payment summary
Includes every booking passing the following criteria:
1. Either check in or deadline date is within the next month from current time.
2. Payment type is VirtualAccount.

Includes information about booking itself, agent and agency, which a booking belongs to.

The summary is sent to specifically configured email addresses. (CcNotificationAddresses)

**Comment by Raibo** [comment]
https://github.com/happy-travel/edo/wiki/Cron-based-services-for-EDO
