### ISSUE TITLE
Rewrite the documentation of Counterparty to Agency

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#851]
Need to rewrite all documentation related to Counterparty to Agency.
https://github.com/happy-travel/edo/wiki/Counterparties-%5C-Counterparty-States

**Comment by Raibo** [comment]
Edited some diagrams due to counterparties no longer exist.

![Agencies relations diagram](https://user-images.githubusercontent.com/8547320/146389659-fb4c66a0-d30c-4db7-8dbc-47772c1ecbc0.png)
![How price changes](https://user-images.githubusercontent.com/8547320/146390112-e17e3600-cad6-4a87-a919-12e6d97ca79e.png)
![Money flow diagram](https://user-images.githubusercontent.com/8547320/146390192-c6aa463c-79ce-4c2a-a409-fb2ee38f2653.png)

**Comment by ViTsvetkova** [comment]
It is thought we need a SubAgency in the scheme. If it is not neccessary it is fine.

**Comment by kirillta** [comment]
LGTM
